version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    machine:
      image: circleci/classic:edge

    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.27.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Set up project environment variables
          command: cp .env.sample .env

      - run:
          name: docker-compose build
          command: docker-compose build

      - run:
          name: docker-compose up
          command: docker-compose up -d

      - run:
          name: Sleep for waiting launch db
          command: sleep 10

      - run:
          name: Setup db
          command: docker-compose exec backend rails db:create db:migrate

      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            docker-compose exec backend bundle exec rspec --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml

      # TODO: machine executor のせいか現状出力されない
      - store_test_results:
          path: /tmp/test-results

      - slack/status:
          fail_only: true
          # mentions: "here"
          # only_for_branches: 'master'

      - run:
          name: docker-compose down
          command: docker-compose down
          when: always
